### ISSUE TITLE
Unstable software

### ISSUE THREAD

**Issue by TypicalZedF** [pushrax/OpenVR-SpaceCalibrator#102]
For a windows 11 user, and a quest 2 user... this software is unstable as hell. Specifically, when my only use case is using it for VRChat.
I have 3.0 Vive trackers with 1.0 base stations.
Issues I've had include completely crashing Steam VR constantly, followed by that black screening of the VR view (Oculus Dash) then when rebooting steam VR, almost all my addons are blocked. Not to mention, the software has a history of entirely just giving up altogether and crashing, at least for me. On top of this, turning the trackers on, then loading up SteamVR crashes the software. Crash, crash, crash. It's a Space calibrator joke at this point among my friends cuz of how often I crash lol. Please maybe make the software more stable in regards to just "space cal" crashing, so it doesn't pull down SteamVR with it.

**Comment by GoByeBye** [comment]
No need to insult the creator by calling this software a joke, he owes you nothing. That's just plain **rude**...

In relation to your actual issue though- I have run the same setup. 3x 3.0 Vive trackers, 1x 1.0 base station from HTC and a Quest 2. I've since moved on to a Quest Pro but the issue is not replicable on my system including when using my old Quest 2. (Switched October 2022 to Pro used [this](https://github.com/pushrax/OpenVR-SpaceCalibrator/releases/tag/v1.4) release on both. Also running Windows 11

While I have had the "same" issue it has only happened when some other issue with SteamVR has caused a crash and OVR isn't able to shut down properly. So it seems the root cause of this problem is not with OVR SpaceCalibrator but in fact something else that seems to be acting up on your system.

I suggest you run a [corruption check](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e) on your computer. 

Worst case scenario if you're 100% convinced that this is an issue you could always **[fix the "problem" yourself](https://www.dataschool.io/how-to-contribute-on-github/)** and contribute


:)

**Comment by TypicalZedF** [comment]
I've run corrupted checks on my computer, and I've also tried uninstalling Oculus Software, and Steam VR software. You were right to a point, it did fix some of my constant crashes, but, some still remained. I didn't mean to come off as rude, and I 100% understand that the developer of this software is not obligated to do anything as it's basically free. I'd love to fix the "problem" myself. However, I have no coding know-how, other than Python, and Lua.
