### ISSUE TITLE
WMD positioning centered to lighthouse playspace

### ISSUE THREAD

**Issue by sepiroth887** [pushrax/OpenVR-SpaceCalibrator#16]
Hi,

First of amazing job on this tool! I just got an hp reverb and just had to get rid of the abysmal controllers. 

My previous Vive lighthouses and controllers work fine with SteamVR for xplane 11 but with DCS I have a grey screen anytime I start which seams to be due to some weird boundary translation relative to the lighthouses. 

When viewing the play space I can see the lighthouses in relation to the WMD and their real physical location. And that's where my question lies: 

Is it possible to center the wmd inside the lighthouse boundary with the correct orientation to allow apps that seem to rely on chaperone bounds working correctly? 

I tried using the Vive controller as the reference since it is indeed correctly orienting itself inside the lighthouse boundary before I calibrated it with the hp reverb controllers as the reference. 

I'm thinking if I can use the vivecontroller as a reference somehow to calibrate the headset but it would leave the controller with the wrong offset to my hand holding it. 

Any clever ideas I could use here? 

Thanks!

**Comment by pushrax** [comment]
Sorry for the delay in answering this. Can you confirm which steps you followed from https://github.com/pushrax/OpenVR-SpaceCalibrator#calibration? This seems like the kind of issue that should be fixed by the chaperone copy/paste system. There was a change (https://github.com/pushrax/OpenVR-SpaceCalibrator/commit/9c4a906ec069b896ab1a2c6865073291a11022be) made in v1.0 of the calibrator (after this issue was created) that might also improve things.
