### ISSUE TITLE
Target device is not tracking, Aborting calibration!

### ISSUE THREAD

**Issue by BirdVideos** [pushrax/OpenVR-SpaceCalibrator#29]
My trackers are green and everything else is on. but Space Calibrator keeps Giving me the message ''Target device is not tracking, Aborting calibration!'' this has been happening for a while now not sure if its a me problem or SteamVr

**Comment by pushrax** [comment]
Hi there,

SteamVR can be finicky - this is unfortunately not something that can be fixed in Space Calibrator and is instead related to SteamVR setup.

For help troubleshooting SteamVR I would recommend asking in the Discord group, there are a lot of helpful people there and it’s much easier to troubleshoot real time in chat. https://discord.gg/m7g2Wyj
