### ISSUE TITLE
Face & Face Movement Support

### ISSUE THREAD

**Issue by DemonRem** [pushrax/OpenVR-SpaceCalibrator#32]
hey can you add face motions support?

**Comment by pushrax** [comment]
Can you be more specific about what you would like supported?

**Comment by DemonRem** [comment]
well , i wish will support in record facial data like head movement , lips movement and expression

**Comment by pushrax** [comment]
What hardware setup and goals do you have in mind? Do you mean to implement face tracking with a raw camera stream? What is the desired output format? Overall, recording/exporting face tracking data seems unrelated to the goals of OpenVR-SpaceCalibrator, since there's no OpenVR API for face tracking, and existing systems already fuse face tracking with HMD tracking. I'm interested in learning more about your use case though.

**Comment by DemonRem** [comment]
Well i mean using the rift to read the face data expression head movement (rotation)
Additional is record all the movement as fbx or bvh animation format

**Comment by pushrax** [comment]
This particular project serves a niche of hardware cross-compatibility. Though I have been interested in that as well for another project of mine. It's possible I will implement it at some point in the future in a different repository.

If you know a little bit of C#, I would recommend using Unity for this.
